### ISSUE TITLE
Are any plans to upload the dataloader file for vatex dataset?

### ISSUE THREAD

**Issue by ppanzx** [Ziyang412/UCoFiA#4]

**Comment by 010610-GGG** [comment]
Traceback (most recent call last):
  File "main_ucofia.py", line 554, in <module>
    main()
  File "main_ucofia.py", line 527, in main
    tr_loss, global_step = train_epoch(epoch, args, model, train_dataloader, device, n_gpu, optimizer,
  File "main_ucofia.py", line 266, in train_epoch
    loss = model(input_ids, segment_ids, input_mask, video, video_mask)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 930, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/UCoFiA-main/train/modules/modeling_ucofia.py", line 178, in forward
    (sequence_output, seq_features), visual_output , visual_pixel_output = self.get_sequence_visual_output(input_ids, token_type_ids, attention_mask, 
  File "/UCoFiA-main/train/modules/modeling_ucofia.py", line 241, in get_sequence_visual_output
    visual_output , visual_pixel_output = self.get_visual_output(video, video_mask, shaped=True, video_frame=video_frame)                  # [bs, num_frames, dim]
  File "/UCoFiA-main/train/modules/modeling_ucofia.py", line 223, in get_visual_output
    visual_pixel = self.visual_token_selector(visual_pixel)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/UCoFiA-main/train/modules/differential_topk.py", line 115, in forward
    pred_score = self.score_predictor(x, self.max_frames).squeeze() # (bs*max_frames, n_patches)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
请问这个错误如何解决

**Comment by Ziyang412** [comment]
Hi, updated. Please also refer to for more details 
https://github.com/LiuRicky/ts2_net/blob/master/scripts/run_vatex.sh
